version: 2

updates:
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: mix
    rebase-strategy: auto
    schedule:
      interval: daily
      time: "08:00"
      timezone: "America/Phoenix"
    assignees:
      - smartrent/maintainers
    reviewers:
      - smartrent/maintainers
    insecure-external-code-execution: allow
    registries:
      - smartrent-hex-org

registries:
  smartrent-hex-org:
    type: hex-organization
    organization: smartrent
    key: ${{secrets.HEX_PM_SECRET}}
