name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MIX_ENV: test

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        elixir-version: '1.11.4'
        otp-version: '23.3.2'
    - name: Restore dependencies and build cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.mix
          _build
          !_build/test/lib/solicit
          deps
          priv/plts
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Build
      run: mix compile --warnings-as-errors
    - name: Check formatting
      run: mix format --check-formatted
    - name: Lint
      run: mix lint
    - name: Run Dialyzer
      run: mix dialyzer
    - name: Run tests
      run: mix test
